# Live browser showcase generated from Three.jl scene objects.
#
# Run:
#   julia --project=. examples/live_webgl_showcase.jl
#
# Open:
#   examples/output/live_webgl_showcase.html

import Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Three

const OUT = joinpath(@__DIR__, "output")
isdir(OUT) || mkpath(OUT)

function positions_geometry(points)
    positions = Float64[]
    for p in points
        append!(positions, (p.x, p.y, p.z))
    end
    BufferGeometry(positions, Float64[], Float64[], collect(1:length(points)), length(points), 0)
end

function build_instancing_case()
    scene = Scene(background=Color3(0.006, 0.008, 0.012))

    floor = Mesh(PlaneGeometry(width=17.0, height=17.0, width_segments=4, height_segments=4),
                 MeshStandardMaterial(color=Color3(0.22, 0.24, 0.28), roughness=0.9);
                 name="floor")
    floor.rotation = Euler(-pi/2, 0.0, 0.0)
    add!(scene, floor)

    inst = InstancedMesh(IcosahedronGeometry(radius=0.42),
                         MeshStandardMaterial(color=Color3(0.28, 0.82, 1.0), metalness=0.15, roughness=0.35),
                         9 * 9)
    k = 0
    for ix in 1:9, iz in 1:9
        x = (ix - 5) * 0.9
        z = (iz - 5) * 0.9
        y = 0.55 + 0.5 * sin(0.9*x + 0.7*z)
        k += 1
        set_instance_matrix!(inst, k,
            mat4_translation(x, y, z) *
            mat4_rotation_y(0.45*x) *
            mat4_rotation_x(0.25*z) *
            mat4_scaling(0.85, 0.85, 0.85))
    end
    add!(scene, inst)

    WebGLExportCase("instancing", "Instancing + OrbitControls",
                    "InstancedMesh generated by Three.jl and rendered interactively.",
                    scene; target=Vec3(0.0, 0.65, 0.0), radius=8.5, height=4.8, fov=pi/4)
end

function build_particles_case()
    scene = Scene(background=Color3(0.0, 0.0, 0.0))
    pts = Vec3{Float64}[]
    for i in 1:360
        t = 0.19 * i
        r = 0.024 * i
        y = 0.014 * i - 2.5
        push!(pts, Vec3(r*cos(t), y, r*sin(t)))
    end
    add!(scene, PointsObject(positions_geometry(pts),
                             PointsMaterial(color=Color3(0.62, 0.88, 1.0), size=3.0)))

    WebGLExportCase("particles", "Particles",
                    "Three.jl PointsObject exported to live WebGL.",
                    scene; target=Vec3(0.0, 0.1, 0.0), radius=8.2, height=1.8, fov=pi/3.1)
end

function build_postfx_case()
    scene = Scene(background=Color3(0.055, 0.060, 0.075))
    floor = Mesh(PlaneGeometry(width=17.0, height=19.0, width_segments=4, height_segments=4),
                 MeshStandardMaterial(color=Color3(0.42, 0.45, 0.52), roughness=0.88);
                 name="floor")
    floor.rotation = Euler(-pi/2, 0.0, 0.0)
    add!(scene, floor)

    colors = [Color3(0.95, 0.35, 0.26), Color3(0.26, 0.72, 0.96),
              Color3(0.95, 0.78, 0.24), Color3(0.46, 0.86, 0.48)]
    for row in 1:4, col in 1:4
        z = -4.5 + 2.1 * row
        x = -3.6 + 2.3 * col
        radius = 0.42 + 0.05 * row
        mat = MeshStandardMaterial(color=colors[mod1(row + col, length(colors))],
                                   metalness=0.15, roughness=0.42)
        obj = isodd(row + col) ?
            Mesh(SphereGeometry(radius=radius, width_segments=28, height_segments=18), mat) :
            Mesh(TorusKnotGeometry(radius=radius, tube=0.13, tubular_segments=48, radial_segments=8), mat)
        obj.position = Vec3(x, radius + 0.05, z)
        obj.rotation = Euler(0.2row, 0.35col, 0.1row)
        add!(scene, obj)
    end

    WebGLExportCase("postfx", "Geometry Gallery",
                    "Three.jl SphereGeometry and TorusKnotGeometry in a live orbit view.",
                    scene; target=Vec3(0.1, 0.6, 0.2), radius=9.0, height=4.2, fov=pi/4.5)
end

function build_keyframe_case()
    scene = Scene(background=Color3(0.01, 0.012, 0.018))
    floor = Mesh(PlaneGeometry(width=14.0, height=14.0, width_segments=4, height_segments=4),
                 MeshStandardMaterial(color=Color3(0.18, 0.20, 0.24), roughness=0.92);
                 name="floor")
    floor.rotation = Euler(-pi/2, 0.0, 0.0)
    add!(scene, floor)

    for x in -3.0:1.5:3.0, z in -3.0:1.5:3.0
        h = 0.7 + mod(abs(x*7 + z*3), 5) * 0.24
        tower = Mesh(BoxGeometry(width=0.55, height=h, depth=0.55),
                     MeshStandardMaterial(color=Color3(0.12, 0.14, 0.18), roughness=0.7))
        tower.position = Vec3(x, h/2, z)
        add!(scene, tower)
    end

    tracks = AbstractKeyframeTrack[]
    times = [0.0, 2.0, 4.0, 6.0, 8.0]
    looppts(phase) = [Vec3(3.8*cos(2pi*t/8 + phase), 0.45, 2.7*sin(2pi*t/8 + phase)) for t in times]
    for i in 1:4
        car = Mesh(BoxGeometry(width=0.62, height=0.34, depth=0.34),
                   MeshStandardMaterial(color=i == 1 ? Color3(0.92, 0.28, 0.20) : Color3(0.23, 0.52, 0.82),
                                        roughness=0.45);
                   name="train_car_$i")
        add!(scene, car)
        push!(tracks, KeyframeTrack(car, :position, times, looppts(0.22i)))
    end

    drone = Mesh(SphereGeometry(radius=0.23, width_segments=20, height_segments=12),
                 MeshStandardMaterial(color=Color3(0.24, 0.78, 1.0), roughness=0.3);
                 name="drone")
    add!(scene, drone)
    push!(tracks, KeyframeTrack(drone, :position, times,
        [Vec3(0.0, 2.2, 0.0), Vec3(1.5, 2.9, -1.4), Vec3(-1.8, 2.6, -1.1),
         Vec3(-1.2, 3.1, 1.4), Vec3(0.0, 2.2, 0.0)]; interpolation=:cubic))

    sign = Mesh(BoxGeometry(width=0.8, height=0.14, depth=0.8),
                MeshBasicMaterial(color=Color3(1.0, 0.70, 0.20), side=:double);
                name="sign")
    sign.position = Vec3(0.0, 1.15, 0.0)
    add!(scene, sign)
    push!(tracks, KeyframeTrack(sign, :scale, [0.0, 0.7, 1.4],
        [Vec3(0.8, 0.8, 0.8), Vec3(1.25, 1.25, 1.25), Vec3(0.8, 0.8, 0.8)]))
    push!(tracks, QuaternionKeyframeTrack(sign, :rotation, [0.0, 2.0, 4.0],
        [Quaternion(), quat_from_euler(0.0, pi, 0.0), quat_from_euler(0.0, 2pi, 0.0)]))

    clip = AnimationClip("city_loop", tracks)
    WebGLExportCase("keyframes", "Keyframe City",
                    "AnimationClip and KeyframeTrack data exported from Three.jl.",
                    scene; target=Vec3(0.0, 0.9, 0.0), radius=9.2, height=4.7, fov=pi/4.2,
                    animations=[clip])
end

function main()
    cases = [build_instancing_case(), build_particles_case(), build_postfx_case(), build_keyframe_case()]
    html = save_webgl_html(joinpath(OUT, "live_webgl_showcase.html"), cases)
    println("LIVE_WEBGL_SHOWCASE_OK $html")
end

main()
